name: flutter_resume
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.9.0 <4.0.0'
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  provider: ^6.0.5
  go_router: ^8.0.5
  intl: ^0.20.2
  oktoast: ^3.4.0
  flutter_easyloading: ^3.0.5
  device_preview: ^1.2.0
  url_launcher: 6.1.12
  cached_network_image: ^3.3.0
  shared_preferences: ^2.2.2
  json_annotation: ^4.8.0
  flutter_staggered_grid_view: ^0.7.0
  dio: ^5.3.3
  easy_refresh: ^3.4.0
  flutter_syntax_view: ^4.0.0
  rxdart: ^0.27.7
  flutter_localized_locales: ^2.0.4
  image: ^4.0.17
  crypto: ^3.0.3
  photo_manager: 3.7.1
  photo_manager_image_provider: ^2.2.0
  photo_view: ^0.14.0
  path_provider: ^2.1.2
  video_thumbnail: ^0.5.3
  video_player: ^2.8.2
  flutter_local_notifications: ^17.2.4
  extended_tabs: ^4.1.0
  just_audio: ^0.9.38
  flutter_rust_bridge: 2.11.1
  waterfall_flow: ^3.1.1
  pull_to_refresh_notification: ^3.1.1
  loading_more_list: ^7.1.0
  flame: ^1.30.1
  flame_audio: ^2.0.0
  vector_math: ^2.2.0

  palette:
    path: plugins/palette
  screen_security:
    path: plugins/screen_security
  rust_lib_flutter_resume:
    path: rust_builder

dependency_overrides:
  flutter_spinkit: 5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.7.1
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/images/
    - assets/images/card/
    - assets/videos/
    - assets/audio/
    - assets/audio/neon_shooter/
  shaders:
    - assets/shaders/pixelation.frag
